### PR TITLE
fix: update links in head and *isLoaded to true

### PR DESCRIPTION
**Pull request by monteri**
**Description:**

Describe what this pull request changes, and why. Include implications for people using this change.

**Merge checklist:**

- [ ] Consider running your code modifications in the included example app within `frontend-platform`. This can be done by running `npm start` and opening http://localhost:8080.
- [ ] Consider testing your code modifications in another local micro-frontend using local aliases configured via [the `module.config.js` file in `frontend-build`](https://github.com/openedx/frontend-build#local-module-configuration-for-webpack).
- [ ] Verify your commit title/body conforms to the conventional commits format (e.g., `fix`, `feat`) and is appropriate for your code change. Consider whether your code is a breaking change, and modify your commit accordingly.

**Post merge:**

- [ ] After the build finishes for the merged commit, verify the new release has been pushed to [NPM](https://www.npmjs.com/package/@edx/frontend-platform).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @monteri!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @monteri! Just flagging that there's a couple failing checks.

**Comment by mphilbrick211** [comment]
> Hi @monteri! Just flagging that there's a couple failing checks.

Hi @monteri! Friendly ping on this.

**Comment by mphilbrick211** [comment]
Hi @monteri - could you try rebasing this PR? It might help the codecov checks pass. If it doesn't work, I'll look into it for you.

**Review by adamstankiewicz — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@monteri 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-platform&entry.867055334=https://github.com/openedx/frontend-platform/pull/534&entry.1484655318=https://github.com/monteri&entry.752974735=2023-08-09+15:46&entry.1917517419=2023-12-09+19:08&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by adamstankiewicz** [comment]
@Mashal-m Thanks for checking in on this PR. It's a bug fix against the branch in #440.

**Pull request merged**
