### PR TITLE
build: upgrade codecov from v3 to v4, use secret

### PR DESCRIPTION
**Pull request by kdmccormick**
Per https://openedx.atlassian.net/wiki/spaces/COMM/pages/3438280709/Adding+Codecov, I think this is the right thing to do.

@dcoa , could you review this?

### CODE REVIEW

**Comment by kdmccormick** [comment]
Hm, the Run Coverage step says:
```
Error: Codecov token not found. Please provide Codecov token with -t flag.
```

**Comment by dcoa** [comment]
There is a second file that uses codecov too, [manual-publish.yml ](https://github.com/openedx/frontend-platform/blob/master/.github/workflows/manual-publish.yml#L29)

**Comment by kdmccormick** [comment]
@dcoa how does this look?

**Review by dcoa — APPROVED** [review]
Looks good to me, thanks @kdmccormick

**Pull request merged**
