### PR TITLE
refactor: browserslist extended in package.json

### PR DESCRIPTION
**Pull request by Mashal-m**
Browser list has extended in package.json file

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Mashal-m!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Comment by natabene** [comment]
@Mashal-m Thank you for your contributions. Once your agreement has been processed, we will be able to review your code.

**Comment by natabene** [comment]
@arbrandes I believe this one would be for your team.

**Comment by natabene** [comment]
@arbrandes Good to go - please review.

**Pull request closed without merging**
