### PR TITLE
Draft - MFE configuration at runtime

### PR DESCRIPTION
**Pull request by felipemontoya**
**Description:**

This draft PR serves as a discussion holder for the work of making mfes capable of being configured during runtime instead of during build.

**Merge checklist:**

- [ ] Gather some consensus on the approach

**Post merge:**

- [ ] After the build finishes for the merged commit, verify the new release has been pushed to [NPM](https://www.npmjs.com/package/@edx/frontend-platform).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @felipemontoya! I've created [OSPR-6679](https://openedx.atlassian.net/browse/OSPR-6679) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by natabene** [comment]
@felipemontoya Just checking if you are still planning on resuming work on this PR.

**Comment by felipemontoya** [comment]
Thanks a lot for bringing my attention to this @natabene. This PR was only a placeholder for some other work that ended up being merged in https://github.com/openedx/frontend-platform/pull/335.
I'll close this now.

**Comment by openedx-webhooks** [comment]
@felipemontoya Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-platform&entry.867055334=https://github.com/openedx/frontend-platform/pull/330&entry.1484655318=https://github.com/felipemontoya&entry.752974735=2022-05-13+08:58&entry.1917517419=2022-07-19+20:54&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
