### PR TITLE
feat/ add Vietnamese support language

### PR DESCRIPTION
**Pull request by DAN3002**
**Description:**

In our edx-plasform app, we need VIetnamese support language (in MFE). So this PR will add vi locate into i18n

**Merge checklist:**

- [x] Consider running your code modifications in the included example app within `frontend-platform`. This can be done by running `npm start` and opening http://localhost:8080.
- [x] Consider testing your code modifications in another local micro-frontend using local aliases configured via [the `module.config.js` file in `frontend-build`](https://github.com/edx/frontend-build#local-module-configuration-for-webpack).
- [x] Verify your commit title/body conforms to the conventional commits format (e.g., `fix`, `feat`) and is appropriate for your code change. Consider whether your code is a breaking change, and modify your commit accordingly.

**Post merge:**

- [x] After the build finishes for the merged commit, verify the new release has been pushed to [NPM](https://www.npmjs.com/package/@edx/frontend-platform).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @DAN3002! I've created [OSPR-6785](https://openedx.atlassian.net/browse/OSPR-6785) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Comment by natabene** [comment]
@DAN3002 Thank you for the PR. Once your CLA forms have been processed, we will be able to review your code.

**Comment by natabene** [comment]
@DAN3002 This is now ready for our review, I will line this up with our internal teams.

**Comment by mphilbrick211** [comment]
Flagging this PR as it's been inactive for a while. Looks like it has not been looked at by 2U. Just seeing if it's still necessary?

CC: @Carlos-Muniz @openedx/fed-bom

**Review by BilalQamar95 — APPROVED** [review]

**Review by ishahroz — CHANGES_REQUESTED** [review]
Example app and build working fine. Also tested in consuming MFEs, working fine. Only thing that is required is, test case need to be updated as it is failing for new language "Vietnamese" in frontend-platform.

**Comment by DAN3002** [comment]
@ishahroz Hi, 
So i need to update test case for Vietnamese in repo call "frontend-platform" and not this repo right?

**Comment by ishahroz** [comment]
> @ishahroz Hi, So i need to update test case for Vietnamese in repo call "frontend-platform" and not this repo right?

@DAN3002 When you try to run test cases for `frontend-platform` locally, you will see failure and some warnings related to `Vietnamese` language support. So, need to update failing and warning test suites in order to incorporate `Vietnamese` language. And yes, these test cases will be updated in this repo (which is `frontend-platform`).

**Comment by mphilbrick211** [comment]
Hi @DAN3002! Friendly follow-up on the requested changes.

**Comment by mphilbrick211** [comment]
Hi @DAN3002! Just checking back on this to see if changes were made and/or this is ready to review? Thanks!

**Comment by mphilbrick211** [comment]
@arbrandes @ishahroz - we have not heard back from this author - are we still going to pursue this PR?

**Comment by arbrandes** [comment]
@mphilbrick211, I think it's important for community members that propose i18n improvements such as this one to be able to follow up on their contributions.  Otherwise, it would be difficult for us to test that they're working satisfactorily.  Until somebody else steps up to "maintain" vietnamese support, we should probably put this on the backburner.

**Comment by mphilbrick211** [comment]
Closing this for now as it's been inactive.

**Comment by openedx-webhooks** [comment]
@DAN3002 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-platform&entry.867055334=https://github.com/openedx/frontend-platform/pull/344&entry.1484655318=https://github.com/DAN3002&entry.752974735=2022-06-11+07:31&entry.1917517419=2023-06-20+19:38&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
