### PR TITLE
FC-0001: Account pages -> micro-frontend

### PR DESCRIPTION
**Pull request by UvgenGen**
**Description:**

Added ACCOUNT_PROFILE_URL and ACCOUNT_SETTINGS_URL settings.

edx-platform PR: https://github.com/openedx/edx-platform/pull/30336
frontend-component-header PR: https://github.com/openedx/frontend-component-header/pull/210

## Supporting information
https://github.com/openedx/public-engineering/issues/71
Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-17

**Merge checklist:**

- [ ] Consider running your code modifications in the included example app within `frontend-platform`. This can be done by running `npm start` and opening http://localhost:8080.
- [ ] Consider testing your code modifications in another local micro-frontend using local aliases configured via [the `module.config.js` file in `frontend-build`](https://github.com/edx/frontend-build#local-module-configuration-for-webpack).
- [ ] Verify your commit title/body conforms to the conventional commits format (e.g., `fix`, `feat`) and is appropriate for your code change. Consider whether your code is a breaking change, and modify your commit accordingly.

**Post merge:**

- [ ] After the build finishes for the merged commit, verify the new release has been pushed to [NPM](https://www.npmjs.com/package/@edx/frontend-platform).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @UvgenGen! I've created [OSPR-6652](https://openedx.atlassian.net/browse/OSPR-6652) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@dianakhuang I believe this is with your team, so please review and merge when you have a chance.

**Review by abdullahwaheed — APPROVED** [review]
LGTM!

**Comment by openedx-webhooks** [comment]
@UvgenGen 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-platform&entry.867055334=https://github.com/openedx/frontend-platform/pull/326&entry.1484655318=https://github.com/UvgenGen&entry.752974735=2022-05-02+14:03&entry.1917517419=2022-12-08+09:35&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
